In [1]:
import numpy as np
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [2]:
ch_arr2=np.array(["Supervised","unSupervised","sEMi-supervised","reinforcement"])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')

In [3]:
cleaned_arr=np.char.replace(low_arr,"-"," ")
cleaned_arr

array(['supervised', 'unsupervised', 'semi supervised', 'reinforcement'],
      dtype='<U15')

In [5]:
array1=np.array([1,2,3])
array1.dtype

dtype('int32')

In [6]:
low_arr.dtype

dtype('<U15')

In [15]:
 array8=np.array([1,2,3,4],dtype='i')

In [8]:
array8

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex64)

In [10]:
array2conv=array8.astype('f')

C:\Users\students\AppData\Local\Temp\ipykernel_1908\3503831993.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  array2conv=array8.astype('f')


In [11]:
array2conv

array([1., 2., 3., 4.], dtype=float32)

In [17]:
array3conv=array8.astype('U1')

In [18]:
array3conv

array(['1', '2', '3', '4'], dtype='<U1')

numone=np.ones((3,3))

In [25]:
numone=np.ones((3,3),dtype='int')
numone

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [37]:
random2=np.random.random(3)
random3=random2.astype('int')
random3

array([0, 0, 0])

In [84]:
import random
random.randint(1,100)

19

dimones=np.ones((4,3,2))

In [87]:
dimones=np.ones((4,3,2))
dimones

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [88]:
ar1 = np.array([1,2,3])
ar2 = np.array([2,4,6])
add = ar1+ar2

In [89]:
add

array([3, 6, 9])

In [91]:
power= np.power(ar1,ar2)
power

array([  1,  16, 729])

In [99]:
range_array=np.arange(0,10,3)
print(range_array)
np.random.randint(1,100)

[0 3 6 9]


63

In [101]:
b=np.random.randint(low=1,high=6,size=(2,3))
b

array([[1, 1, 1],
       [4, 5, 1]])

In [105]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.concatenate([arr1,arr2])

array([1, 2, 3, 4, 5, 6])

In [106]:
np.info(np.ndarray.ndim)


Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3
